### ISSUE TITLE
Launcher behaves weird at dpi>600 aka tablet mode

### ISSUE THREAD

**Issue by Jobatphysics** [SuperiorOS/android_packages_apps_Launcher3#1]
![Screenshot_20220930-112638.png](https://user-images.githubusercontent.com/94097278/193201923-dc9586de-dcdc-4d1a-a6e7-72f10109bacb.png)

**Comment by Darkstar085** [comment]
This ROM isn't made for tablets.. Use 460 dpi max

**Comment by Jobatphysics** [comment]
Lol
