### ISSUE TITLE
fix always on display's Time bracket

### ISSUE THREAD

**Issue by Priyanshi-ga** [SuperiorOS/android_packages_apps_Launcher3#2]
when AOD is on, there's an issue during 10,11, 12th etc hour that at the last there's a square bracket "[" drawing beside it..

my device is oneplus nord (avicii) and I request u to fix this issue

**Comment by Darkstar085** [comment]
> when AOD is on, there's an issue during 10,11, 12th etc hour that at the last there's a square bracket "[" drawing beside it..
> 
> my device is oneplus nord (avicii) and I request u to fix this issue

Thats not our issue googles implementation is borked.. if u don't wanna that then use stock font
